package model.generator.generators;

import model.generator.Generator;

public class NissGenerator extends Generator {
	
	public NissGenerator() {
		this.setName( "Niss Generator" );
	}
	
	@Override
	public String generateLoot() {
		return "Cool loot has been generated by niss :)";
	}
}