package model.generator.generators;

import gui.controller.tabs.NissGeneratorTabController;
import model.generator.Generator;

public class NissGenerator extends Generator {

    private NissGeneratorTabController ngtc;
    private String[] values;

	public NissGenerator(NissGeneratorTabController ngtc) {

	    this.setName( "Niss Generator" );
	    setNgtc(ngtc);
	}

    @Override
	public String generateLoot() {
	    for(String value : ngtc.getValues()){
	        System.out.println(value);
        }
		return "Cool loot has been generated by niss :)";
	}


    // --- Getter and Setter ----------------------------------------------------------------------

    private void setNgtc(NissGeneratorTabController ngtc){
        this.ngtc = ngtc;
    }

    private NissGeneratorTabController getNgtc(){
        return this.ngtc;
    }
}